---
- hosts: all
  tasks:
  - name: Single line PowerShell
    win_shell: Set-Content -Path C:\temp\test.txt -Value 'Hello there. '

  - name: Run multi-lined shell commands
    win_shell: |
        $text = Get-Content C:\Temp\test.txt
        $text += ' General Kenobi....you are a bold one'
        Set-Content -Path C:\Temp\test2.txt -Value $text
    register: cmdresult
  - debug: var=cmdresult.stdout

  - name: Copy a single file
    win_copy:
      src: "{{ playbook_dir }}/files/test.ps1"
      dest: C:\Temp\test.ps1
 

  - name: Run a script
    win_shell: C:\temp\test.ps1
    register: myresult    
  
  - debug: var=myresult.stdout_lines
